# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db79962c96293e9ffb1bd521d131944e31cb2d622cb2164befa18537940c9fe2a539e14bcf062065d8977089ce375dc4b4755cc752a8ead149aac2f7c9a58a00

test:
  secret_key_base: 354d7693de6c471a876068fe8f39d32cc5f74b3c26fa40ce1f839db45a8009681ad55a2283dac19c7483088ba5b6ecc57a45bd26b774f540f661ad2e9a7db8bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
